server:
    port: ${PORT:5000}
spring:
    security:
        oauth2:
            client:
                registration:
                    google:
                        clientId: 337530417957-2duko0bfs2873vv7k5nlrqdtsaqe5ufv.apps.googleusercontent.com
                        client-secret: 337530417957-2duko0bfs2873vv7k5nlrqdtsaqe5ufv.apps.googleusercontent.com
                        redirectUri: 337530417957-2duko0bfs2873vv7k5nlrqdtsaqe5ufv.apps.googleusercontent.com
    application:
        name: club-administration
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
    data:
        mongodb:
            uri: mongodb://root:root@ac-ikvttqa-shard-00-00.vsyhddu.mongodb.net:27017,ac-ikvttqa-shard-00-01.vsyhddu.mongodb.net:27017,ac-ikvttqa-shard-00-02.vsyhddu.mongodb.net:27017/club-administration?ssl=true&replicaSet=atlas-9zq0nu-shard-0&authSource=admin&retryWrites=true&w=majority
            #uri: mongodb://localhost:27017/admin
club:
    origins: https://club-administration-front-hn3t-40hb66go9-ijchavez.vercel.app,https://club-administration-front.vercel.app,https://club-administration-front-hn3t.vercel.app,http://localhost:4200,http://localhost:5000
platform:
    jwtSecret: publishSecretKey
    jwtExpirationMs: 86400000
    secretPassword: Showar123!456*ñasdAsd
